services:
  cutepikachu-server-mysql:
    image: mysql:8.4.2
    container_name: cutepikachu-server-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  cutepikachu-server-redis-stack-server:
    image: redis/redis-stack-server:7.4.0-v0
    container_name: cutepikachu-server-redis-stack-server
    restart: always
    # network_mode: "host"
    ports:
      - "6379:6379"

  cutepikachu-server-nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: cutepikachu-server-nacos
    restart: always
    depends_on:
      - cutepikachu-server-mysql
    # network_mode: "host"
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=cutepikachu-server-mysql
      - MYSQL_SERVICE_DB_NAME=cutepikachu_cn_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
      - NACOS_AUTH_ENABLE=true
      - NACOS_CORE_AUTH_PLUGIN_NACOS_TOKEN_SECRET_KEY=Y3V0ZXBpa2FjaHVjbnNlcnZlcmN1dGVwaWthY2h1Y25zZXJ2ZXI=
      - NACOS_CORE_AUTH_SERVER_IDENTITY_KEY=cutepikachucnservercutepikachucnserver
      - NACOS_CORE_AUTH_SERVER_IDENTITY_VALUE=cutepikachucnservercutepikachucnserver
    volumes:
      - ./nacos/logs:/home/nacos/logs

  cutepikachu-server-minio:
    image: minio/minio:RELEASE.2024-09-09T16-59-28Z
    container_name: cutepikachu-server-minio
    restart: always
    command: server /data --console-address ":9001"
    # network_mode: "host"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456