
spring:
  datasource:
    dynamic:
      primary: cutepikachu_cn_biz
      datasource:
        cutepikachu_cn_biz:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/cutepikachu_cn_biz?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
          username: root
          password: root

# 项目配置
cutepikachu:
  biz:
    oss:
      minio:
        endpoint: http://127.0.0.1:9000
        access-key: iAm7zszjZRZpYXaLMBVP
        secret-key: ROll1R3uvTTXV0KU57w74e7wWNEVozUAqXv78S1j