spring:
  datasource:
    dynamic:
      primary: cutepikachu_cn_ai
      datasource:
        cutepikachu_cn_ai:
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/cutepikachu_cn_ai?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
          username: root
          password: root
  cloud:
    ai:
      tongyi:
        connection:
          api-key: api-key
  ai:
    zhipuai:
      api-key: api-key
