
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cutepikachu_cn_auth?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root

# 项目配置
cutepikachu:
  security:
    routers:
      auth:
        - match: /**